-- ============================================================================
-- Hợp đồng · Link thư mục ảnh ĐÃ CHỈNH SỬA (giao khách) nhập TAY
-- Chạy trên Supabase (SQL Editor). An toàn khi chạy lại (idempotent).
--
-- Bối cảnh: khi hợp đồng chuyển sang giai đoạn GIAO KHÁCH, ảnh giao khách lấy từ
-- thư mục "File ChinhSua". Với studio KHÔNG dùng Đồng bộ Drive tự động, cột này
-- cho phép studio dán TAY link thư mục ảnh đã chỉnh sửa ngay trên hợp đồng; hệ
-- thống tự dựng album giao khách từ link đó. Album chọn ảnh (JPG gốc) khi ấy tự
-- thành "ảnh gốc" hiển thị bên trong album giao khách để khách xem/tải trên Drive.
-- ============================================================================
alter table public.studio_contracts add column if not exists edited_drive_url text;
