/**
 * Thứ tự các bảng khi sao lưu / khôi phục toàn hệ thống.
 * QUAN TRỌNG: bảng cha đứng trước bảng con để khi khôi phục (upsert theo thứ tự)
 * khóa ngoại luôn tồn tại trước khi chèn bản ghi tham chiếu tới nó.
 */
export const BACKUP_TABLES = [
  "profiles",
  "site_settings",
  "sites",
  "site_blocks",
  "albums",
  "album_sources",
  "photos",
  "selections",
  "album_shares",
  "album_creations",
  "feedback",
  "bookings",
  "upgrade_requests",
  "filter_usages",
  "compress_usages",
  "discount_codes",
  "discount_redemptions",
  "affiliate_codes",
  "affiliate_commissions",
  "message_templates",
  "studio_contracts",
  "contract_items",
  "contract_crew",
  "contract_equipment",
  "contract_products",
  "contract_quote_options",
  "contract_payment_plan",
  "contract_payments",
  "contract_tasks",
  "contract_edit_requests",
  "contract_client_proofs",
  "contract_templates",
  "contract_template_items",
  "studio_crew",
  "crew_unavailable",
  "studio_events",
  "studio_bookings",
  "studio_equipment",
  "studio_packages",
  "studio_pricelist",
  "studio_services",
  "studio_expenses",
  "studio_quotes",
  "quote_items",
  "quote_adjustments",
  "studio_notifications",
  "desktop_devices",
  "wedding_invitations",
  "wedding_rsvps",
  "story_pages",
  "story_wishes",
  "story_uploads",
] as const;

export type BackupTable = (typeof BACKUP_TABLES)[number];
